name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 8
        uses: actions/setup-java@v2.3.0
        with:
            distribution: 'temurin'
            java-version: '8'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradle cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        run: |
          ./gradlew --build-cache build
      - name: List files
        run: ls
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Latest Build
          path: ./build/libs/*.jar
